version: '3'

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/database/

  api:
    build: ./api
    restart: always
    ports:
      - "5000:5000"

  webapp:
    build: ./webapp
    restart: always
    ports:
      - "3000:3000"