name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: bash scripts/up.sh
  lint-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          cd api/
          npm i
          cd -
          cd webapp/
          npm i
          cd -
          bash scripts/up.sh
          cd webapp/
          yarn run lint
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          cd api/
          npm i
          cd -
          cd webapp/
          npm i
          cd -
          bash scripts/up.sh
          cd api/
          yarn run lint
  test-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          cd api/
          npm i
          cd -
          cd webapp/
          npm i
          cd -
          bash scripts/up.sh
          cd webapp/
          yarn run test:e2e
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: bash scripts/run-db-test.sh